### ISSUE TITLE
Supplementaries wall lanterns render incorrectly

### ISSUE THREAD

**Issue by WenXin20** [Low-Drag-MC/Shimmer#10]
### Minecraft Version

`v1.18.2`

### Shimmer version

`v0.4`

### Modpack info or mod list

https://gist.github.com/WenXin20/c00fd3ee04cf9acbb1f053bb72ff7e82

### The latest.log file

https://gist.github.com/WenXin20/e25eb98622f7a32159a697345ad95769

### Mod Versions

`Rubidium v0.5.2a`
`Flywheel v0.6.2`
[`Supplementaries v1.4.2`](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[`Selene v1.17.4`](https://www.curseforge.com/minecraft/mc-mods/selene)

### Issue description

- When a lantern is placed on the wall, it renders completely black. 
- Supplementaries adds the ability for lanterns to be placed on walls.
- A temporary workaround is to set `fast_mode` to `true` in the `supplementaries_client` config.

### Steps to reproduce

1. Grab a lantern
2. Place on a wall

### Other information

![image](https://user-images.githubusercontent.com/12000593/172438784-4319c45e-674d-4520-a073-1ff4ce09aeb4.png)

**Comment by zomb-676** [comment]
tested with
Rubidium 0.5.2a
flywheel 1.18-0.6.2.66
Selence 1.18.2-1.17.4
Supplementaries 1.18.2-1.4.2
![image](https://user-images.githubusercontent.com/26162862/173060034-cb581179-c133-43a5-b67c-6c82482b99e0.png)
maybe it is other mod's fault
can you provide more information or dissguss at discord ?

**Comment by WenXin20** [comment]
Oh weird, I'll do more testing to see if another mod is involved

**Comment by WenXin20** [comment]
I tested it with only Selene, Supplementaries, & Shimmer and had the same issue
![2022-06-11_00 29 33](https://user-images.githubusercontent.com/12000593/173174858-8c99d159-d7d7-444c-b4bb-6e7b7c255e35.png)
And at the same time I found another bug where the bloom everywhere actually only happens if rubidium is **_not_** installed.

**Comment by WenXin20** [comment]
![2022-06-11_00 53 36](https://user-images.githubusercontent.com/12000593/173175147-a0fb070d-f898-4f91-9152-6046f6114bef.png)

**Comment by zomb-676** [comment]
can you find anything like `OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated.'` in the game console output?
can you update the latest.log again only with Selene, Supplementaries, & Shimmer installed

**Comment by WenXin20** [comment]
Here it is:
https://gist.github.com/WenXin20/ccadb8001ff8a301871bb5988406be40#file-latest-log-L85
I didn't see anything like that, but I did notice something else related to Shimmer

**Comment by Yefancy** [comment]
@WenXin20 whats your gpu?

**Comment by Yefancy** [comment]
@WenXin20 whats your gpu?

**Comment by WenXin20** [comment]
It is AMD Ryzen 5 5500U Radeon Graphics

**Comment by Yefancy** [comment]
thanks, we almost sure this is an AMD GPU compatibility issue.
[Shimmer-forge-1.18.2-0.0.6.jar.zip](https://github.com/Low-Drag-MC/Shimmer/files/8929193/Shimmer-forge-1.18.2-0.0.6.jar.zip)
I have no amd graphics, so i build a new version for test. 
Could you use this one load the game once, and update the config file `shimmer-client.toml` that `"Block Bloom Effect" = false`.
Restart the game and see what happens with the bloom effect?
This is not a fix, but it will help us locate the error we made.

**Comment by WenXin20** [comment]
Ok, I'll give it a try tonight after work :)

**Comment by Yefancy** [comment]
tyvm

**Comment by Yefancy** [comment]
> I tested it with only Selene, Supplementaries, & Shimmer and had the same issue ![2022-06-11_00 29 33](https://user-images.githubusercontent.com/12000593/173174858-8c99d159-d7d7-444c-b4bb-6e7b7c255e35.png) And at the same time I found another bug where the bloom everywhere actually only happens if rubidium is **_not_** installed.

besides, whether the bloom effect works well when the rb installed? like, whether the redstone dust get the bloom properly?

**Comment by Yefancy** [comment]
[Shimmer-forge-1.18.2-0.0.6.1.jar.zip](https://github.com/Low-Drag-MC/Shimmer/files/8934795/Shimmer-forge-1.18.2-0.0.6.1.jar.zip)
Try this and see if your issues are solved

**Comment by Yefancy** [comment]
use the latest version (v0.1.0)，modify shimmer-client.toml configuration ("MRT Reversed" = true).

**Comment by WenXin20** [comment]
Thanks!
