### ISSUE TITLE
Bloom particles often turn black（泛光粒子经常变黑）

### ISSUE THREAD

**Issue by Kiuju79** [Low-Drag-MC/Shimmer#115]
### Minecraft Version

1.19.2 forge

### ModLoader

Forge

### Shimmer version

 Shimmer-forge-1.19.2-0.1.14

### Modpack info or mod list(please reduce mod range)

Embeddium

### The latest.log file and hs_err_pidXXX if exists

no

### Issue description

Bloom particles often turn black.
（泛光粒子经常变成纯黑色）
![1](https://github.com/Low-Drag-MC/Shimmer/assets/122474664/a4d7be29-d008-4c47-9bdb-9292868f70b3)

### Steps to reproduce

1. 多次生成粒子(不确定)，泛光粒子有低概率变黑，需要重载资源包或重启游戏。

2. 重载资源包，反光粒子也有概率变黑，需要再次重载资源包或重启游戏。

**Comment by Kiuju79** [comment]
经过测试在没有安装Embeddium的情况下触发概率小了很多，但依然会触发。

**Comment by zomb-676** [comment]
fix by 416b601d

**Comment by zomb-676** [comment]
https://github.com/Low-Drag-MC/Shimmer/blob/416b601d366f5bf4f9d8392a4ebbbb39e1fc66a3/Forge/src/main/java/com/lowdragmc/shimmer/forge/core/mixins/ForgeParticleEngineMixin.java#L94-L100
