### ISSUE TITLE
Game crashes with SEF

### ISSUE THREAD

**Issue by tunikakeks** [Low-Drag-MC/Shimmer#126]
### Minecraft Version

1.20.1

### ModLoader

Forge

### Shimmer version

every version of 2.*

### Modpack info or mod list(please reduce mod range)

worldedit-mod-7.2.15
geckolib-forge-1.20.1-4.4.7
architectury-9.2.14-forge
Theatrical-forge-1.0.0-alpha.22-build.81+mc1.20.1
player-animation-lib-forge-1.0.2-rc1+1.20
S.E.F_Mod-v.3.4_1.20.1-FORGE
cloth-config-11.1.118-forge
flywheel-forge-1.20.1-0.6.10-7 (included from create)
sound-physics-remastered-forge-1.20.1-1.4.5
create-1.20.1-0.5.1.f
and ofc shimmer

### The latest.log file and hs_err_pidXXX if exists

https://pastebin.com/F9U0qESL

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

latest create (integrated flywheel)

### Issue description

it crashes on startup

### Steps to reproduce

1. start minecraft

**Comment by ComputerhullGaming** [comment]
Create mod causes no issue for me. However SEF Mod (Stage Equipment Fornitures) conflicts with shimmer.

**Comment by tunikakeks** [comment]
seems to be fixed with newer SEF versions
