### ISSUE TITLE
Item Entity not updating light bug

### ISSUE THREAD

**Issue by Mysticpasta1** [Low-Drag-MC/Shimmer#13]
### Minecraft Version

1.18.2

### Shimmer version

Custom Shimmer Fork of Shimmer-1.18.2-0.4

### Modpack info or mod list

N/A

### The latest.log file

N/A

### optifine , Rubidium , flywheel or any rendering related mods. mod versrion is required.

currently in a dev environment

### Issue description

Unless a block is place only the item entities and entities from the resulting glowing pink light from the apple with show.

### Steps to reproduce

Throw apple
let it start glowing 
place mobs around it and see them pink

### Other information

![2022-06-10_23 49 03](https://user-images.githubusercontent.com/45608372/173221491-32bce30e-9481-4684-bea0-4d1a212827e0.png)
![2022-06-12_01 47 59](https://user-images.githubusercontent.com/45608372/173221492-5e3a9c81-d0fc-4010-8520-f17982ebd897.png)
From github -> https://github.com/Mysticpasta1/Shimmer

**Comment by Mysticpasta1** [comment]
I hope to PR this as soon as the lighting update bug is gone

**Comment by Mysticpasta1** [comment]
update methods tried 
level#sendBlockUpdated
levelRenderer#setBlocksDirty

**Comment by Mysticpasta1** [comment]
I think I found out how to issue occur LightManager isn't firing on an item entering and leaving the world

**Comment by Mysticpasta1** [comment]
nevermind that isn't it

**Comment by Yefancy** [comment]
It has nothing to do with MBD, you should learn how Shimmer works first.
