### ISSUE TITLE
Crash when watch it in mod list

### ISSUE THREAD

**Issue by qznfbnj** [Low-Drag-MC/Shimmer#15]
### Minecraft Version

1.18.2

### Shimmer version

Shimmer-1.18.2-0.1.0

### Modpack info or mod list

none

### The latest.log file

https://gist.github.com/qznfbnj/287074c0c669fe41c1b83d254d244b45

### optifine , Rubidium , flywheel or any rendering related mods. mod versrion is required.

catalogue-1.6.2-1.18.2

### Issue description

启动游戏后，主屏幕点击模组按钮进入模组列表，选择 Shimmer 时崩溃，forge版本 40.1.51
崩溃报告：https://gist.github.com/qznfbnj/7d0af6d29e0656811a678bc0027b6d72

### Steps to reproduce

1. 安装 forge 40.1.51
2. 安装 Shimmer 0.1.0
3. 启动游戏，主屏幕点击模组按钮进入模组列表，选择 Shimmer
4. 崩溃

### Other information

将 mods.toml 中的 logoFile="assets/shimmer/icon.png" 改成 logoFile="icon.png" 并移动 icon.png 后，进入模组列表选择 Shimmer 不会崩溃，但是它的版本号变成 0.0NONE，不知道为什么
但是安装 catalogue-1.6.2-1.18.2 后，主屏幕点击模组按钮仍然崩溃，而且是点击后直接崩溃。
继续将 #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" 改成 displayURL="https://www.curseforge.com/minecraft/mc-mods/shimmer" 后，主屏幕点击模组按钮能正常显示模组列表

**Comment by Yefancy** [comment]
thanks for point it out

**Comment by Yefancy** [comment]
fixed in the latest version
