### ISSUE TITLE
Crash with my custom modpack

### ISSUE THREAD

**Issue by EchoPyre** [Low-Drag-MC/Shimmer#17]
### Minecraft Version

1.18.2

### Shimmer version

Shimmer-forge-1.18.2-0.1.3.jar

### Modpack info or mod list

https://pastebin.com/7g0r8jke

### The latest.log file

https://pastebin.com/uHtqazJ1

### optifine , Rubidium , flywheel or any rendering related mods. mod versrion is required.

I have rubidium-0.5.2a.jar. I dont know what other rendering mods i would have.

### Issue description

Crash right before opening

### Steps to reproduce

Just open the game

### Other information

Sorry for duping but my other issue was closed and i was told to reopen it if it wasnt working and it still isnt 0n 1.1.2

**Comment by Yefancy** [comment]
any latest log.files

**Comment by EchoPyre** [comment]
no change

**Comment by EchoPyre** [comment]
atleast i think so so il update it anyways

**Comment by Yefancy** [comment]
i dont think you can get the same log with the 0.1.2. send me the latest log?

**Comment by EchoPyre** [comment]
i did

**Comment by Yefancy** [comment]
we reproduced it, will fix it in the next version

**Comment by EchoPyre** [comment]
was not fixed in 0.1.3

**Comment by Yefancy** [comment]
yep, It's still being discussed, we think it might be another mod that's causing the issue, but Shimmer is mistaken for the culprit. We're trying to figure out how to do it better, and I'll let you know when it's fixed

**Comment by zomb-676** [comment]
please try the latest version 0.1.4 https://www.curseforge.com/minecraft/mc-mods/shimmer/files/3856862  
if the error still occurs, please re-send the entire latest.log file instead of the crash-report file
after analyzing,  we think it is the other mod's fault,  while shimmer is mistaken.
we only can diagnose the true reason from the entire latest.log file.

**Comment by EchoPyre** [comment]
0.1.4 worked thank u
