### ISSUE TITLE
[Question] Can you configure fluid blocks in config

### ISSUE THREAD

**Issue by Saereth** [Low-Drag-MC/Shimmer#2]
Is it possible and if so how do you configure the lighting or bloom effects for a liquid source like lava for example? Thanks for the info, mod is super interesting so far!

**Comment by Yefancy** [comment]
I did forgot the fluid.
Thank you for your suggestion, very interesting idea, I will update for fluid support.

![2022-05-27_15 29 56](https://user-images.githubusercontent.com/18493855/170652323-82c29c51-9769-4685-91f9-4f3d534b56f1.png)
