### ISSUE TITLE
我应该怎么将效果作用于物品

### ISSUE THREAD

**Issue by FurryRbl** [Low-Drag-MC/Shimmer#20]
我应该怎么将发光效果作用于物品而不是方块？
例如钻石剑

**Comment by Yefancy** [comment]
wiki里面，有介绍怎么创建彩色光源，自己创建的彩色光源，此外，新版本自己维护的彩色光源下在移动、修改光照强度时，要调度区块的光照更新，（或者配置文件中设置useLigthMap = fase，可以不用调度光照更新）

**Comment by FurryRbl** [comment]
> wiki，里面，创建自己的彩色光源，创建自己的光源，另外，新的维护彩色光源在移动的下、修改介绍的时候，需要创建一个点亮的版本，（或者配置中如何设置使用 Lith 的地图更新，） fase，可以不用提醒更新）

Wiki貌似少了一条配置
```groovy
//没有这条不然会找不到钠的Maven包
maven {
    url 'https://cfa2.cursemaven.com'
}
```

**Comment by Yefancy** [comment]
不理解，但shimmer并不要求强制和纳一起使用
