### ISSUE TITLE
[Bug] [1.18.2 fabric] offhand torch glitch/issue

### ISSUE THREAD

**Issue by JoostMSoftware** [Low-Drag-MC/Shimmer#22]
### Minecraft Version

1.18.2

### Shimmer version

Shimmer-fabric-1.18.2-0.1.9

### Modpack info or mod list

https://pastebin.com/9cS98tmk

### The latest.log file

https://pastebin.com/SRJaYEGy

### Issue description

Good day shimmer dev team, 

I wanted to try out shimmer but noticed something off when I put a torch into my offhand: https://streamable.com/fz5te5 < this is a recording I made with the latest version of shimmer and some other [mods](https://pastebin.com/9cS98tmk) installed. 

I assume this is unwanted behavior with the torch?

### Steps to reproduce

grab a torch from the creative tab or use /give etc

put it in your offhand

behold the weirdness

**Comment by Yefancy** [comment]
fixed in the latest version (0.1.9-hotfix)
