### ISSUE TITLE
Start-up crash with Create/Flywheel

### ISSUE THREAD

**Issue by Jorgee9001** [Low-Drag-MC/Shimmer#23]
### Minecraft Version

1.18.2

### Shimmer version

Shimmer-forge-1.18.2-0.1.9.jar

### Modpack info or mod list

Only Create, Flywheel, and Shimmer

### The latest.log file

https://pastebin.com/PEUCHpN9

### optifine , Rubidium , flywheel or any rendering related mods. mod versrion is required.

Flywheel: flywheel-forge-1.18-0.6.4.jar

Create: create-mc1.18.2_v0.5.0c.jar

### Issue description

Game loads and then crashes immediately upon reaching title screen. Game exists with following error code:

![image](https://user-images.githubusercontent.com/44140284/180064526-4fa7c608-6e42-4aaf-a90c-f70409fecc32.png)

### Steps to reproduce

1. Install Create, Flywheel, and Shimmer as per versions above.
2. Launch Minecraft

### Other information

This version of Shimmer is the hotfix version

**Comment by zomb-676** [comment]
fix ad0674e8dc44e0fbe3fdf95ab7bfffbf8c042d17
