### ISSUE TITLE
Special rendering for some mods is wonky

### ISSUE THREAD

**Issue by tlitookilakin** [Low-Drag-MC/Shimmer#24]
### Minecraft Version

1.18.2

### Shimmer version

0.1.10

### Modpack info or mod list

https://www.curseforge.com/minecraft/modpacks/moonlitmyths

### The latest.log file

https://mclo.gs/ZvsVOaL

### optifine , Rubidium , flywheel or any rendering related mods. mod versrion is required.

Flywheel 1.18-0.6.4.87
(the modpack comes with oculus and rubidium but I have removed these for stability reasons.)

### Issue description
all create components that aren't full-block modelshave a hazy glow

### Steps to reproduce
place an andesite shaft from Create

**Comment by zomb-676** [comment]
should fix on version [0.1.11](https://www.curseforge.com/minecraft/mc-mods/shimmer/files/4020772)
