### ISSUE TITLE
with blur mod the console gets filled real quick

### ISSUE THREAD

**Issue by dadoirie** [Low-Drag-MC/Shimmer#25]
### Minecraft Version

1.18.2

### Shimmer version

1.18.2-0.1.10

### Modpack info or mod list

only shimmer with blur

### The latest.log file

https://mclo.gs/8PSjReE

### Issue description

uploaded log says everthing

### Steps to reproduce

just load those 2 mods together and join a world

**Comment by zomb-676** [comment]
fix 16e07b9312b2113d305039a833663bfac66c250f
