### ISSUE TITLE
Unknown rendering issue.

### ISSUE THREAD

**Issue by deadspidervenom** [Low-Drag-MC/Shimmer#27]
### Minecraft Version

1.18.2

### Shimmer version

0.1.10

### Modpack info or mod list

https://www.curseforge.com/minecraft/modpacks/create-flavored

### The latest.log file

[latest.log](https://github.com/Low-Drag-MC/Shimmer/files/9456791/latest.log)

### optifine , Rubidium , flywheel or any rendering related mods. mod versrion is required.

Only mod i know of is Flywheel, but it still occuring with it off

### Issue description

Only colored light i am getting is the torch when i hold it.

### Other information

I did add mod and update mods inside the back, but either they only dealt with sound, or i have them disable.

Currently enabled mods are in the these screenshots
![image](https://user-images.githubusercontent.com/12871122/187548090-c234a28c-e1b2-487a-a060-58620599ecbd.png)
![image](https://user-images.githubusercontent.com/12871122/187548125-fd260a21-178e-4c2a-b90c-2e98737f964f.png)

**Comment by zomb-676** [comment]
caused by [AlexsMobs](https://github.com/AlexModGuy/AlexsMobs)  
they set lava's render type: solid -> translucent, which is currently not supported by shimmer
[link](https://github.com/AlexModGuy/AlexsMobs/blob/75486550ebf34f51d4ea5ccd8cd9526466786dd2/src/main/java/com/github/alexthe666/alexsmobs/ClientProxy.java#L256-L259) and code snap:
```java
//required for lava vision
RenderType lavaType = RenderType.translucent();
ItemBlockRenderTypes.setRenderLayer(Fluids.LAVA, lavaType);
ItemBlockRenderTypes.setRenderLayer(Fluids.FLOWING_LAVA, lavaType);
```

**Comment by zomb-676** [comment]
the lava should be the only influenced one, maybe you can see if bloom works fine on redstone dust
