### ISSUE TITLE
Crashes with my custom fabric mod pack

### ISSUE THREAD

**Issue by Dr01000111** [Low-Drag-MC/Shimmer#28]
my mods list

[Fabric]+Wildfire+Female+Gender+Mod-2.9.jar"
AdditionalAdditions-4.0.5.jar"
AirHop-v3.2.0-1.18.2-Fabric.jar"
alternate-current-mc1.18-1.4.0.jar"
Amplified_Nether_v1.1.1.jar"
appleskin-fabric-mc1.18.2-2.4.1.jar"
architectury-4.8.82-fabric.jar"
auudio_fabric_1.0.3_MC_1.18-1.18.2.jar"
badpackets-fabric-0.1.2.jar"
balm-fabric-3.2.0+0.jar"
bclib-1.4.7.jar"
bedrockify-1.4.1+mc1.18.2.jar"
betterbiomeblend-1.18.2-1.3.5-fabric.jar"
better-end-1.1.1.jar"
BetterF3-1.2.5-Fabric-1.18.2.jar"
bottleyourxp-fabric_1.18.2-2.0.jar"
bsvsb-2.0.5.jar"
cammies-minecart-tweaks-1.5.jar"
Capes-1.3.1+1.18.2.jar"
cem-0.7.1.jar"
charm-fabric-1.18.2-4.2.2.jar"
chesttracker-1.18.2-1.1.16.jar"
CITResewn-1.1.1+1.18.2.jar"
cleancut-1.18.2-5.0-fabric.jar"
CleanView-1.18.2-v1.jar"
clientsidenoteblocks-2.1+1.18.jar"
cloth-api-3.2.64.jar"
Clumps-fabric-1.18.2-8.0.0+15.jar"
collective-fabric-1.18.2-4.36.jar"
continuity-2.0.1+1.18.2.jar"
create-1.18.2-0.5.0c-708.jar"
createaddition+1.18.2-1.18.2-20220813a.jar"
CullLessLeaves-1.0.1.jar"
discord helper.jar"
drippyloadingscreen_fabric_1.6.4_MC_1.18-1.18.2
dual_riders-1.18.2-1.1.1-fabric.jar"
duckling-1.0.6-forge.jar"
easiervillagertrading-1.18.2-fabric0.47.10-1.5.
enchantedshulkers-1.0.1+1.18.2.jar"
entityculling-fabric-mc1.18-1.5.1.jar"
Essential-fabric_1-18-2.jar"
exlinefurniture-fabric-1.18.2-v2.3.0.jar"
extrakeybinds-1.18.2-0.2.0.jar"
fabric-api-0.58.0+1.18.2.jar"
fabric-carpet-1.18.2-1.4.69+v220331.jar"
fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar"
ferritecore-4.2.1-fabric.jar"
flytre_lib-1.18.2-1.8.2-fabric.jar"
forgetmechunk-1.0.4-1.18.X-1.19.X.jar"
friendsandfoes-fabric-mc1.18.2-1.4.5.jar"
geckolib-fabric-1.18.2-3.0.35.jar"
herdspanic-1.0.5.jar"
horse-stats-vanilla-4.1.10.jar"
HWGMod-1.18.2-1.1.11.jar"
IKnowWhatImDoing-4.1.0-fabric.jar"
illuminations-1.10.4.jar"
immersive-portals-1.4.9-mc1.18.2-fabric.jar"
indium-1.0.7+mc1.18.2.jar"
inventorio-1.18-fabric-1.7.1.jar"
iris-mc1.18.2-1.2.7.jar"
jam-lib-0.0.5.jar"
konkrete_fabric_1.5.0_MC_1.18-1.18.2.jar"
krypton-0.1.9.jar"
lambdynamiclights-2.1.0+1.17.jar"
lazydfu-0.1.2.jar"
LibraryFerret-Fabric-1.18.2-2.5.1.jar"
light-overlay-6.0.5.jar"
lithium-fabric-mc1.18.2-0.7.10.jar"
malilib-fabric-1.18.2-0.12.1.jar"
memoryleakfix-1.18.2-0.7.0.jar"
midnightcontrols-1.5.0+1.18.jar"
modmenu-3.2.3.jar"
moreculling-1.18.2-0.8.2.jar"
mountedpearl-1.18-1.0.0.jar"
notenoughcrashes-4.1.6+1.18.2-fabric.jar"
numeralping-1.0.3.jar"
Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4.2.jar
ohmygoat-fabric-1.18.2-1.1.0.jar"
Origins-1.18.2-1.4.1.jar"
Origins-Classes-1.18.2-1.3.0.jar"
Pehkui-3.4.0+1.14.4-1.19.2.jar"
PresenceFootsteps-1.5.1.jar"
PuzzlesLib-v3.3.5-1.18.2-Fabric.jar"
ratsmischief-1.3.7.jar"
recast-fabric_1.18.2-1.9.jar"
reeses_sodium_options-1.4.6+mc1.18.2-build.54.j
replanter-fabric-1.18.2-1.3.jar"
RoughlyEnoughItems-8.3.529.jar"
screenshot-to-clipboard-1.0.9-fabric.jar"
Shimmer-fabric-1.18.2-0.0.5.jar"
shulkerboxtooltip-3.0.8+1.18.2.jar"
simplechunkloader-1.0.1.jar"
smoothboot-fabric-1.18.2-1.7.0.jar"
sodium-extra-0.4.8+mc1.18.2-build.56.jar"
sodium-fabric-mc1.18.2-0.4.1+build.15.jar"
starlight-1.0.2+fabric.89b8d9f.jar"
TerraBlender-fabric-1.18.2-1.1.0.102.jar"
TinySkeletons-v3.2.1-1.18.2-Forge.jar"
toms_storage_fabric-1.18.2-1.3.4.jar"
trade-cycling-fabric-1.18.2-1.0.2.jar"
UniversalBoneMeal-v3.0.5-1.18.2-Fabric.jar"
VisualWorkbench-v3.3.0-1.18.2-Fabric.jar"
waystones-fabric-1.18.2-10.1.0.jar"
WI-Zoom-1.4-MC1.18.2.jar"
worldedit-mod-7.2.10.jar"
wthit-fabric-4.13.1.jar"
Xaeros_Minimap_22.13.0_Fabric_1.18.2.jar"
XaerosWorldMap_1.26.2_Fabric_1.18.2.jar"
YungsApi-1.18.2-Fabric-2.0.8.jar"
YungsBetterDungeons-1.18.2-Fabric-2.1.0.jar"
YungsBetterMineshafts-1.18.2-Fabric-2.2.jar"
YungsBetterStrongholds-1.18.2-Fabric-2.1.1.jar"

https://pastebin.pl/view/6a13e8dc

**Comment by Dr01000111** [comment]
I updates to a newer version of shimmer and im still crashing i just noticed that i tried a old version

**Comment by Dr01000111** [comment]
nvm it was immersive portals and its being worked on

**Comment by zomb-676** [comment]
both shimmer(colored light) and immersive portal([portal clip](https://qouteall.fun/immptl/wiki/Implementation-Details.html#front-clipping)) need to transform the shaders' source codes, but no API is
provided for this requirement. 
Sodium uses [its class ShaderLoader](https://github.com/CaffeineMC/sodium-fabric/blob/73b3f45d064ee96dae459bc2a3f604d4f5495407/src/main/java/net/caffeinemc/sodium/render/shader/ShaderLoader.java) and replaces vanilla's
so with and without Sodium has different problems

# shimmer + immersive portal 

mixin conflict
shimmer: [Inject Program.compileShaderInternal](https://github.com/Low-Drag-MC/Shimmer/blob/268cfc70d2511c2b6bc2cbd27ba8cc1bcce0fb6b/Common/src/main/java/com/lowdragmc/shimmer/core/mixins/ProgramMixin.java#L47-L87)
immersive portal: [Overwrite Program.compileShaderInternal](https://github.com/iPortalTeam/ImmersivePortalsMod/blob/f29ba4bad1a81c160164e2076b4f38bb9106070c/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/mixin/client/render/shader/MixinProgram.java#L21-L55)

**MixinApplyError occurred and crashed**

---
# shimmer + immersive portal + Sodium

shimmer: [Inject ShaderLoader.loadShader](https://github.com/Low-Drag-MC/Shimmer/blob/4e746de4ceba7c984cd28c8cb631ebb95e52d185/Fabric/src/main/java/com/lowdragmc/shimmer/fabric/core/mixins/sodium/ShaderLoaderMixin.java#L22-L34)
immersive portal: same

the result is that, if shimmer transforms the shader, the **setReturnValue** makes the logic skip the immersive portal's transformation, thus the `gl_ClipDistance` sentence is not injected with an error `uniform imm_ptl_ClippingEquation not found in transformed sodium shader ` which causes the rendering problem 

![image](https://user-images.githubusercontent.com/26162862/190297287-724473ac-ff2d-4773-a814-91a61b98311c.png)

**Comment by oliverrook** [comment]
I can state that with the forge version of immersive portals + rubidium (the forge version of sodium) I crash upon loading into the world.

**Comment by zomb-676** [comment]
this issue is closed, please open a new issue following the issue template
