### ISSUE TITLE
A couple on-launch crashes

### ISSUE THREAD

**Issue by StillCreative** [Low-Drag-MC/Shimmer#29]
I try to launch this mod with Dashloader and a few seconds into launch I get a bunch of lines saying

[Render thread/WARN]: @Redirect conflict. Skipping dashloader.mixins.json:option.cache.shader.GameRendererMixin from mod dashloader->@Redirect::shaderCreation(Lnet/minecraft/class_5912;Ljava/lang/String;Lnet/minecraft/class_293;)Lnet/minecraft/class_5944; with priority 69, already redirected by shimmer.mixins.json:GameRendererMixin from mod shimmer->@Redirect::redirectReloadShaders(Lnet/minecraft/class_5912;Ljava/lang/String;Lnet/minecraft/class_293;)Lnet/minecraft/class_5944; with priority 1000

However, if I launch without Dashloader then it crashes and nothing in the log mentions shimmer. It may be important to mention I'm using an M1 Macbook Air, so it may be at fault here, as it doesn't tend to play nice with some rendering mods.

[Crash With Dashloader.log](https://github.com/Low-Drag-MC/Shimmer/files/9762788/Crash.With.Dashloader.log)

[Crash Without Dashloader.log](https://github.com/Low-Drag-MC/Shimmer/files/9762789/Crash.Without.Dashloader.log)

If it's better to include the text instead of the files let me know

**Comment by zomb-676** [comment]
can your run shimmer without Dashloader again and send the debug.log?

**Comment by StillCreative** [comment]
I got on a separate computer account and ran it on its own and it worked fine, so it seems it's something with another mod I have. Likely sodium, though I didn't see any of that whole line of code that was mentioned in the more recent bug report.

**Comment by StillCreative** [comment]
Still did crash with dashloader though, but it cited something about "indigo" which I didn't purposefully install.

**Comment by zomb-676** [comment]
compatible with dashloader will soon
for sodium and fabic-api(including the [indigo](https://github.com/FabricMC/fabric/tree/1.19.2/fabric-renderer-indigo)) should have full compatible, just send debug.log if they crashed

**Comment by zomb-676** [comment]
should be fixed
0b6f45a4dccc726ce471f4bd5c6d0f54b68b274a
