### ISSUE TITLE
Crash on startup with 0.1.13

### ISSUE THREAD

**Issue by JLUsr** [Low-Drag-MC/Shimmer#30]
### Minecraft Version

1.19.2

### ModLoader

Fabric

### Shimmer version

Shimmer-fabric-1.19.2-0.1.13

### Modpack info or mod list(please reduce mod range)

fabric-api-0.62.0+1.19.2.jar

### The latest.log file and hs_err_pidXXX if exists

https://gist.github.com/JLUsr/1141e0fd29c8022f45e30b6db1f7ba43

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

None

### Issue description

Crash on launch with latest version of shimmer for fabric 1.19.2

### Steps to reproduce

1. Add Shimmer-fabric-1.19.2-0.1.13.jar to your 'mods' folder
2. Launch

### Other information

I am using PolyMC as my launcher if that helps.

**Comment by zomb-676** [comment]
try this https://www.curseforge.com/minecraft/mc-mods/shimmer/files/4028836
wait for curseforge to review
