### ISSUE TITLE
Quilt incompatibility

### ISSUE THREAD

**Issue by slava110** [Low-Drag-MC/Shimmer#32]
### Minecraft Version

1.19.2

### ModLoader

Fabric

### Shimmer version

Shimmer-fabric-1.19.2-0.1.13

### Modpack info or mod list(please reduce mod range)

quilted-fabric-api-4.0.0-beta.14+0.62.0-1.19.2, Shimmer-fabric-1.19.2-0.1.13

### The latest.log file and hs_err_pidXXX if exists

https://gist.github.com/slava110/e10b03ae58f1620cb287733067e78b77

### Issue description

Shimmer doesn't load with Quilt loader

### Steps to reproduce

1. Install Shimmer
2. Install Quilted Fabric API
3. Crash

### Other information

Quilt Loader: 0.17.5-beta.6

**Comment by zomb-676** [comment]
Quilt is in beta currently 
No plan for supporting it until it is stable

**Comment by slava110** [comment]
![image](https://user-images.githubusercontent.com/26705162/199665574-1b2741b9-4edd-42c4-a961-6e4178ad9c19.png)
So now?

**Comment by zomb-676** [comment]
![image](https://user-images.githubusercontent.com/26162862/199758036-893d8162-c1d4-4a04-b854-d8057ff4d946.png)
at least the website no longer has this WIP warning anymore and the API becomes more stable
