### ISSUE TITLE
Game fails to launch.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Low-Drag-MC/Shimmer#34]
### Minecraft Version

1.19.2

### ModLoader

Fabric

### Shimmer version

Shimmer-fabric-1.19.2-0.1.13

### Modpack info or mod list(please reduce mod range)

https://pastebin.com/Gd9ZcSR0

### The latest.log file and hs_err_pidXXX if exists

https://pastebin.com/8tTz3B5C

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

betterfpsdist-fabric-1.19.1-1.9
continuity-2.0.1+1.19
CullLessLeaves-1.0.5
dynamic-fps-2.2.0
enhancedblockentities-0.7.2+1.19.2
Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0
entityculling-fabric-1.5.2-mc1.19
entity-view-distance-1.0.2+1.19
reeses_sodium_options-1.4.7+mc1.19.2-build.59
sodium-extra-0.4.10+mc1.19.2-build.64
sodium-fabric-mc1.19.2-0.4.4+build.18
starlight-1.1.1+fabric.ae22326

### Issue description

Adding Shimmer simply causes Minecraft to not launch. No game window appears at all after clicking the play button in the Minecraft Launcher, so I have to close the process in Task Manager. A crash report is still generated.

[crash-2022-10-27_12.47.16-client.txt](https://github.com/Low-Drag-MC/Shimmer/files/9881688/crash-2022-10-27_12.47.16-client.txt)

### Steps to reproduce

1. Install all the mods I have.
2. Install Shimmer.
3. Attempt to launch game.

**Comment by zomb-676** [comment]
Dash Loader, shimmer use mixin to fast the progress of reloading shader
should be fixed at next version

**Comment by JENOVAAbsolute** [comment]
Thank you.
