### ISSUE TITLE
Some blocks using what is said "accent color" can't be correctly revealed

### ISSUE THREAD

**Issue by sssssLug** [Low-Drag-MC/Shimmer#36]
[latest.log](https://github.com/Low-Drag-MC/Shimmer/files/10040985/latest.log)
![2022-11-18_19 36 37](https://user-images.githubusercontent.com/114668379/202699391-5f9231d5-67d7-49ad-8d6c-c5bc1eab4582.png)
![2022-11-18_19 36 40](https://user-images.githubusercontent.com/114668379/202699431-5ea171f7-f209-46f1-90a8-d35dc2743b47.png)
(i don't know if these infos are enough as an issue)

**Comment by zomb-676** [comment]
I don't know what you want to do  
Maybe you can describe what you want to do  
I think The accentColor and mainColor are the nbt data of the block  
That is different from the blockstate
