### ISSUE TITLE
Crashes when export

### ISSUE THREAD

**Issue by Rad233** [Low-Drag-MC/Shimmer#37]
### Minecraft Version

1.18.2

### ModLoader

Fabric

### Shimmer version

0.1.14

### Modpack info or mod list(please reduce mod range)

1.fabric api 2.shimmer

### The latest.log file and hs_err_pidXXX if exists

https://pastebin.com/ynWpSxfM

### Issue description

Crashes instantly after fllowing the steps below.

### Steps to reproduce

1.Open the shimmer auxiliary screen
2.pick a random block
3.click add button
4.click export button
5.game crash

**Comment by zomb-676** [comment]
will be fixed in the next version
there is something wrong with the JSON serializer
