### ISSUE TITLE
Being able to see Torchlights and Other effects through blocks

### ISSUE THREAD

**Issue by IvorAmlug** [Low-Drag-MC/Shimmer#43]
### Minecraft Version

1.19.2

### ModLoader

Forge

### Shimmer version

0.1.14

### Modpack info or mod list(please reduce mod range)

https://pastebin.com/Qg4pYbzH

### The latest.log file and hs_err_pidXXX if exists

https://pastebin.com/WtSM3W9E

### Issue description

I seem to be able to see Torch particles for Ex. through walls with this mod installed after pickin up an item
![2023-01-04_21 24 23_5](https://user-images.githubusercontent.com/38656481/210643925-9df743f0-a986-4e14-bb20-6df1a7437535.png)
as u might be able to see on the screen there is the flame in the Item shadow.
Thats the flame of the Torch underground.
its only a short amount of time as it basicly bursts in an out so it was hard to catch.

### Steps to reproduce

place a torch (for example, works with quark crystals too if the Bloomin Blocks TP is installed) underground. 
Cover it.
Look at its direction and pick an item up
Profit?

### Other information

I originaly expected it to be an issue with the Bloomin Blocks TP
Or my vanilla shaders.
But i removed any other mods and Texturepacks and at least as my testing goes its a general issue.

**Comment by IvorAmlug** [comment]
After further testing i found this to be an issue with any Shimmer versions i could test (all except the 1.20). Only have tested with forge so far will try fabric soon. 
Since i forgot in the Original Post:
Cpu:Intel i9-9900K
GPU: 2080ti
If anything else might be required tell me
My GPU drivers are always up to date.
Also i asked some of my friends who i play on a server with if they have the same issue and they all said yes so far.
Well as soon as the 1.20 loadin issue is fixed imma try that version too. But currently its seems unfixable for me.
The only way to get rid of it is to Deactivate all Particles. Cause if there is no Particles none can be shown tru walls.

**Comment by IvorAmlug** [comment]
Okay its also a thing for me in Fabric :/

Asked another one of my Friends he said that so far he didnt notice anything strange like that.
The main difference between him and the rest is that he is running on AMD and not NVidia.

**Comment by SiverDX** [comment]
same issue here
removing the `injectCreateParticle` inject avoids the issue
guess the post particles don't cull correctly

**Comment by IvorAmlug** [comment]
Good that at least means its fixable. Ig.

**Comment by IvorAmlug** [comment]
As this seems to be fixed in the 1.20.1 Versions ima close this issue now
