### ISSUE TITLE
Physics Mod Incompatability

### ISSUE THREAD

**Issue by VanderCat** [Low-Drag-MC/Shimmer#44]
As mentioned in haubna/PhysicsMod#473 all physical particles glow. I also noticed glowing ragdolls.
**Steps to reproduce:**
Same as haubna/PhysicsMod#473
**Screenshots:**
![](https://files.catbox.moe/tomwz1.jpg)

**Comment by zomb-676** [comment]
same as Optifine, making compatibility with closed source mod neeeds mush time
