### ISSUE TITLE
Entities' shadow render as full black / lose transparency

### ISSUE THREAD

**Issue by jamesjimmy88** [Low-Drag-MC/Shimmer#5]
As per title.
![2022-05-29_11 47 38](https://user-images.githubusercontent.com/58559532/170862086-a542e42d-f048-4d9d-a409-ab1c5cf5032d.png)
Tested with Shimmer-1.18.2-0.3 on forge 40.1.25

**Comment by Yefancy** [comment]
fixed 56ac3b0e25459a35b6e8e5718916c296ef0e6112
