### ISSUE TITLE
Alex的动物兼容性问题？

### ISSUE THREAD

**Issue by Dr-WeiAL** [Low-Drag-MC/Shimmer#51]
### Minecraft Version

1.18.2

### ModLoader

Forge

### Shimmer version

Shimmer-1.18.2-0.1.14

### Modpack info or mod list(please reduce mod range)

alexsmobs

### The latest.log file and hs_err_pidXXX if exists

https://pastebin.com/YsauLQhB

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

没有

### Issue description

在安装Alex的动物后熔岩的泛光效果就没了
它似乎修改了熔岩？配合了它的熔岩明视

**Comment by zomb-676** [comment]
same as #27

**Comment by Dr-WeiAL** [comment]
> same as #27

测试后发现1.19.2版本没有这个bug，只有在获得熔岩明视buff后才会出现这个bug，也就是这个bug仅限于1.18.2
