### ISSUE TITLE
[1.19.2] Optimization issues. FPS drops when there is a lot of colored light sources on the screen.

### ISSUE THREAD

**Issue by murao-kun** [Low-Drag-MC/Shimmer#62]
### Minecraft Version

1.19.2

### ModLoader

Forge, Fabric

### Shimmer version

0.1.14

### Modpack info or mod list(please reduce mod range)

-

### The latest.log file and hs_err_pidXXX if exists

-

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

Rubidium, flywheel is presented in instance. Same situation when there is also Oculus with shaders disabled.

### Issue description

Colored lights feels good in terms of optimization while there is not a lot of light sources on the screen. When their count rise, fps starting to drop. Most noticable with colored light from lava in the nether.

**Comment by zomb-676** [comment]
shimmer uses forward rendering when shader pack is not used, its performance is not good  
that's why in the wiki we say
>NOTE: Very not recommended add lights for blocks (e.g. grass block) / fluids (e.g. water, lava) ?>generated in large numbers in the world. Because in order to ensure good performance on any graphics >card, we limited the lights count to 2048, and any lights more that will not be rendered.
