### ISSUE TITLE
Crash upon worldload with Inquisitive modpack (forge & fabric abridged pack)

### ISSUE THREAD

**Issue by Liamgrayskull** [Low-Drag-MC/Shimmer#85]
### Minecraft Version

1.20.1

### ModLoader

Forge

### Shimmer version

Shimmer-forge-1.20.1-0.2.0

### Modpack info or mod list(please reduce mod range)

Inquisitive (posted on modrinth)

### The latest.log file and hs_err_pidXXX if exists

https://gist.github.com/Liamgrayskull/d4ee159e630ddb23973089088947d919

### optifine , Rubidium , flywheel or any rendering related mods. mod version is required.

Embeddium 0.2.9 (0.2.10 crashes upon startup regardless of shimmer) Oculus mc1.20.1-1.6.9, Create 1.20.1 0.5.1.f flywheel version packaged within

### Issue description

Game loads fine, but crashes upon worldload- pack utilizes Sinytra Connector, but it shouldn't affect rendering of the mod considering it has a forge version

### Steps to reproduce

Install modpack Inquisitive
Add Shimmer
Open World

**Comment by SiverDX** [comment]
just as a headsup at shimmer devs
the developer of embeddium is generally open to implement compat on their side

see https://github.com/embeddedt/embeddium/wiki/Compatibility

**Comment by Yefancy** [comment]
why your pack have both `embeddium` and `rubidium `? and also `forge` + `fabric`? 
could you test itwith the only latest embeddium installed(0.2.10)

**Comment by SiverDX** [comment]
rubidium is there because of https://github.com/embeddedt/embeddium/blob/20.1/forge/src/main/java/me/jellysquid/mods/sodium/client/RubidiumStub.java

fabric because of https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

**Comment by Yefancy** [comment]
ah I have reproduced it, lemme check it

**Comment by Yefancy** [comment]
try the 0.2.1? to see if it got fixed

**Comment by Liamgrayskull** [comment]
testing 0.2.1 now, latest embeddium currently crashes with the pack due to mixin errors (not embeddiums fault afaik but Sinytra so it shouldn't present any problems) Upon testing with the latest release, it loads and functions! Thank you for the hasty reply!
