### ISSUE TITLE
Chests have bloom by Default

### ISSUE THREAD

**Issue by Saereth** [Low-Drag-MC/Shimmer#9]
In the latest version chests are glowing by default 
![image](https://user-images.githubusercontent.com/9200909/172057570-b688bbf6-947e-4d55-8348-ce8219d44eda.png)

unsure if other blocks are impacted but I havent noticed any others

**Comment by Yefancy** [comment]
seems i cant reprocude it. I think probably conflict with some mods? I have tested it with the flywheel and the rubidium, but no luck.

**Comment by Yefancy** [comment]
Technically, if a block has the bloom effect meaning thist block is an emissive block at least. but the chest shouldnt be emissive (in vanilla).

**Comment by Saereth** [comment]
ok np, I'll run a reduced mod count and see if I can get more info for you to try and pin it down

**Comment by Saereth** [comment]
[modlist.txt](https://github.com/Low-Drag-MC/Shimmer/files/8840325/modlist.txt)
Current modlist is pretty big so if you see anything you suspect might be the cause I'll rip it out, otherwise its binary add/remove for me till I find it :P

**Comment by Yefancy** [comment]
I have no idea. I know less about 1.18+ mods. I think rendering related mods should take precedence. An aside, i just noticed that you are the FTBI author (the best pack i have played in 1.12).

**Comment by Saereth** [comment]
Will do! And yeah I am, glad you enjoyed it! Working on a new pack for 1.18 and glad to have your mod in it!

**Comment by Yefancy** [comment]
FTBI is the longest pack I've ever played with. And I used my FTBI save for my another mod [multiblocked video](https://www.youtube.com/watch?v=L11YpeMOLlQ). I'm looking forward to the new pack you're making.

**Comment by Saereth** [comment]
updated a bunch of mods and it went away soo.. problem solved :P
