### ISSUE TITLE
Colored Light Monitor is always enabled in dev environment

### ISSUE THREAD

**Issue by AlexNijjar** [Low-Drag-MC/Shimmer#92]
I'm adding Shimmer compat to my mod, [Ad Astra](https://github.com/terrarium-earth/Ad-Astra). I've added it to my dev environment; however, every time I launch the game, the colored light monitor overlay appears. I'm able to temporarily get rid of it by running the `/shimmer coloredLightMonitor` command. But this overlay will reappear every time I restart the game.

Looking at the code, it appears that this overlay is always enabled by default in the dev environment: 
https://github.com/Low-Drag-MC/Shimmer/blob/d513c3debfdb931e595d982a4802757a1f0088ff/Common/src/main/java/com/lowdragmc/shimmer/client/light/LightCounter.java#L85

This is fine for Shimmer development, but is problematic for any modder that adds Shimmer to their dev environment. It should either always be disabled by default, or be saved to a config somewhere so that I can close it once and not have to see it again.

<img width="886" alt="Screenshot 2023-12-29 at 3 41 07 AM" src="https://github.com/Low-Drag-MC/Shimmer/assets/61668546/120ea76d-2a30-4d9f-9be0-b60cfc5de924">

**Comment by Yefancy** [comment]
![image](https://github.com/Low-Drag-MC/Shimmer/assets/18493855/59efc8b4-a89e-47ba-84a5-9b2dbb89f7f5)

do it anywhere in you dev project

**Comment by AlexNijjar** [comment]
Sorry, what does this mean? Are you saying that I should manually disable the monitor by setting `LightCounter.Render.enable` to false somewhere in my project?

**Comment by Yefancy** [comment]
> Sorry, what does this mean? Are you saying that I should manually disable the monitor by setting `LightCounter.Render.enable` to false somewhere in my project?

yeah

in your dev
```java
public init() {
    if (isDev() && isShimmerLoaded()) {
        LightCounter.Render.enable = false;
    }
}
```

**Comment by Yefancy** [comment]
btw, a really cool mod you have done
